config/routes.rb
GooglePlace::Application.routes.draw do
   root 'searches#home'
   get 'searches' => 'searches#set_places', as: 'get_places'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :google_place, only: :set_place

  def home

  end

  def set_places
    @results= google_place.search_place.results
    @error_message = google_place.status unless google_place.status == "OK"
    respond_to :js
  end

  private

  def google_place
    GooglePlaces.new(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GooglePlace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/_form.html.erb
<p>
  <b style='color: red;'><%= @error_message %></b>
</p>

</br>
<%#= raise @results.inspect %>
<%- if @results.present? %>
    <%- @results.each do |result| %>
        <p>
          <b>Address :</b> <%= result['formatted_address'] %>
        </p>
    <%-end%>
<%- else %>
    <b>No Result found.</b>
<%-end%>

app/views/searches/home.html.erb
Search for places near a given address.

<%= form_tag get_places_path, method: :get, remote: true do %>
    <p>
      <%= text_field_tag :search, params[:places],
                         autofocus: true, placeholder: 'Address' %>
      <%= submit_tag "Get Near Places", id: 'submit' %>
    </p>
<% end %>
<hr>
<h2>Results</h2>
<div id='results'/>

app/views/searches/set_places.js.erb
$('#results').html('<%=j render 'searches/form' %>');